### ISSUE TITLE
Why glGetIntegerv is not load?

### ISSUE THREAD

**Issue by wheatdog** [MetricPanda/glgen#1]
I really enjoy your minimal OpenGL extension loader!

Here is some questions:
1. Since you use `glGetIntegerv` to get the version, I think you should add `AddCustomToken(FunctionsHash, "glGetIntegerv");`
2. It would be great if 

```
struct OpenGLVersion
{
  int Major;
  int Minor;
};
```

can be changed to

```
typedef struct OpenGLVersion
{
  int Major;
  int Minor;
} OpenGLVersion;
```

so that c programmers will be happier.

**Comment by yxmatic** [comment]
Thank you, fixed.
